import Head from 'next/head';
import Link from 'next/link';
import React, { useContext, useEffect, useState } from 'react';

import { FaCopyright } from 'react-icons/fa';
import { Store } from '../utils/store';

export default function Layout({ title, children }) {
  const { state, dispatch } = useContext(Store);
  const { cart } = state;
  return (
    <>
      <Head>
        <title>{title ? title + ' - KridShop' : 'KridShop'}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex min-h-screen flex-col justify-between">
        <header className="bg-green-800">
          <nav className="flex h-12 justify-between shadow-md items-center px-4">
            <Link href="/">
              <div className="text-lg">Movie Ecommerce</div>
            </Link>
            <div className="flex items-center">
              <Link href="/cart">
                <div className="tag-a p-4">
                  Cart
                  {cart.cartItems.length > 0 && (
                    <span className="rounded-full bg-red-400 px-2 py-1 mx-1">
                      {cart.cartItems.reduce((a, c) => a + c.quantity, 0)}
                    </span>
                  )}
                </div>
              </Link>
            </div>
          </nav>
        </header>
        <main className="container m-auto mt-4 px-4">{children}</main>
        <footer className="flex h-10 justify-center items-center shadow-inner">
          <div className="flex items-center">
            Copyright <FaCopyright className="mx-2" /> 2023 Movie Ecommerce
          </div>
        </footer>
      </div>
    </>
  );
}
